pub static URLS: [(&str, &str); 11] = [
    (
      "zenki",
      "https://catalog.he.u-tokyo.ac.jp/result?q=&type=all&faculty_id=&facet=%7B%22faculty_type%22%3A%5B%22jd%22%5D%7D&page=",
    ),
    (
        "law",
        "https://catalog.he.u-tokyo.ac.jp/result?type=ug&faculty_id=1&page=",
    ),
    (
        "medicine",
        "https://catalog.he.u-tokyo.ac.jp/result?type=ug&faculty_id=2&page=",
    ),
    (
        "engineering",
        "https://catalog.he.u-tokyo.ac.jp/result?type=ug&faculty_id=3&page=",
    ),
    (
        "arts",
        "https://catalog.he.u-tokyo.ac.jp/result?type=ug&faculty_id=4&page=",
    ),
    (
        "science",
        "https://catalog.he.u-tokyo.ac.jp/result?type=ug&faculty_id=5&page=",
    ),
    (
        "agriculture",
        "https://catalog.he.u-tokyo.ac.jp/result?type=ug&faculty_id=6&page=",
    ),
    (
        "economics",
        "https://catalog.he.u-tokyo.ac.jp/result?type=ug&faculty_id=7&page=",
    ),
    (
        "liberal_arts",
        "https://catalog.he.u-tokyo.ac.jp/result?type=ug&faculty_id=8&page=",
    ),
    (
        "education",
        "https://catalog.he.u-tokyo.ac.jp/result?type=ug&faculty_id=9&page=",
    ),
    (
        "pharmacy",
        "https://catalog.he.u-tokyo.ac.jp/result?type=ug&faculty_id=10&page=",
    ),
];
