name: Rust
on: 
  pull_request:
  push:
    branches: [main]

jobs:
  all:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RUSTFLAGS: -D warnings
    defaults:
      run: 
        working-directory: scraper
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            scraper/target
          key: cargo-cache-${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt
      - run: cargo build
      - run: cargo build --release
      - run: cargo test
      - run: cargo clippy
      - run: cargo fmt --check
